---
title: "Writing Functions"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

set.seed(12345)
```

```{r}
x_vec = rnorm(20, mean = 5, sd = .3)
```

Compute z score
```{r}
(x_vec - mean(x_vec)) / sd(x_vec)
```

Write a function to do this!
```{r}
z_score = function(x) {
  
  z = (x - mean(x)) / sd(x)
  
  z
}
```

Check that this works.

```{r}
z_score(x = x_vec)

z_score(x = rnorm(10, mean = 5))
```

Keep checking

```{r, error= TRUE}
z_score(x = 3)

z_score(c("my", "name", "is", "Jeff"))

z_score(c(TRUE, TRUE, FALSE, FALSE))

z_score(iris)
```



## Multiple 

```{r}
mean_and_sd = function(x) {
  if (!is.numeric(x)) {
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  mean_x = mean(x)
  sd_x =  sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}

```

Double check I did this right
```{r}
mean_and_sd(x_vec)
```

### Start getting means and sds

```{r}

x_vec = rnorm(n = 30, mean = 5, sd = .5)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
```

Let's write a function that uses `n`, a true mean, and true SD as inputs.

```{r}
sim_mean_sd = function(n_obs, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n_obs, mean = mu, sd = sigma),
  )
  
  sim_data |> 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
sim_mean_sd(30, 5, 1)
```

### Loading LoTR data
```{r}
lotr_load_and_tidy = function(path, range, movie_name) {
  
  df = readxl::read_excel(path, range = range) |>
    janitor::clean_names() |>
    gather(key = sex, value = words, female:male) |>
    mutate(race = str_to_lower(race),
           movie = movie_name)
  
  df
  
}

lotr_tidy = 
  bind_rows(
    lotr_load_and_tidy("data/LotR_Words.xlsx", "B3:D6", "fellowship_ring"),
    lotr_load_and_tidy("data/LotR_Words.xlsx", "F3:H6", "two_towers"),
    lotr_load_and_tidy("data/LotR_Words.xlsx", "J3:L6", "return_king")) |>
  select(movie, everything())
```







